# Generated by Django 5.0.6 on 2024-06-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now=True)),
                ('img', models.ImageField(null=True, upload_to='gallery')),
            ],
        ),
    ]
