# Generated by Django 4.2.3 on 2024-07-23 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mebelevv", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gallery",
            options={"verbose_name": "экземпляр", "verbose_name_plural": "Галерея"},
        ),
    ]
