# Generated by Django 4.2.3 on 2024-07-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mebelevv", "0002_alter_gallery_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30, verbose_name="Заголовок")),
                (
                    "img",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="form_images",
                        verbose_name="Фото",
                    ),
                ),
            ],
            options={"verbose_name": "Ответ", "verbose_name_plural": "Ответы",},
        ),
        migrations.AlterField(
            model_name="gallery",
            name="date",
            field=models.DateField(auto_now=True, verbose_name="Дата"),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="img",
            field=models.ImageField(
                null=True, upload_to="gallery", verbose_name="Фото"
            ),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="title",
            field=models.CharField(max_length=30, verbose_name="Заголовок"),
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30, verbose_name="Заголовок")),
                (
                    "answers",
                    models.ManyToManyField(
                        max_length=1000, to="mebelevv.answer", verbose_name="Ответы"
                    ),
                ),
            ],
            options={"verbose_name": "Вопрос", "verbose_name_plural": "Вопросы",},
        ),
    ]
