# Generated by Django 4.2.3 on 2024-07-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mebelevv", "0003_answer_alter_gallery_date_alter_gallery_img_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answers", models.JSONField(verbose_name="Ответы")),
                (
                    "phoneNumber",
                    models.CharField(max_length=16, verbose_name="Номер телефона"),
                ),
                (
                    "img",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="users_images",
                        verbose_name="Фото",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ пользователя",
                "verbose_name_plural": "Ответы пользователей",
            },
        ),
    ]
