# Generated by Django 4.2.3 on 2024-07-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mebelevv", "0004_userinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="order",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Порядок вопроса"
            ),
        ),
    ]
